name: Merge Release Into Main
on:
  push:
    branches:
      - 'prod'

env:
    PR_REVIEWER: "trungdlp-wolffun"

jobs:
  main:
    name: Create PR Release to Main
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Create Pull Request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "Merge back `${{ github.ref_name }}` into `${{ github.event.repository.default_branch }}`"
          pr_body: "Automated Pull Request"
          pr_reviewer: ${{ env.PR_REVIEWER }}
          pr_label: "automated"
